version: '3.4'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - /var/www/certbot:/var/www/certbot/:ro
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
      - ./nostr:/nostr:ro
    network_mode: host
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  gitea:
    image: docker.io/gitea/gitea:nightly
    container_name: gitea
    restart: always
    environment:
      DISABLE_REGISTRATION: "true" # change to true for first installation
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6177:3000"
      - "2233:22"
  # tor:
  #   build: ./tor
  #   restart: always
  #   network_mode: host
  #   volumes:
  #     - ./tor/data:/var/lib/tor
  #     - ./tor/torrc:/etc/tor/torrc
  certbot:
    image: certbot/certbot:latest
    restart: always
    volumes:
      - /var/www/certbot/:/var/www/certbot/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # RoboSats Client App (connects to federation coordinators)
  robosats-client:
    image: recksato/robosats-client:v0.8.2-alpha
    container_name: robosats-client
    restart: always
    environment:
      - TOR_PROXY_IP=127.0.0.1
      - TOR_PROXY_PORT=9050
    volumes:
      - ./robosats-client-data:/usr/src/robosats/data
    network_mode: host

volumes:
  robosats_postgres_data:
  robosats_redis_data:

